# Site settings
title: El programador loco
email: ezapana.marquez@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Este blog esta dedicado a compartir informacion sobre temas 
  bastante puntuales, espero te sean de utilidad y sobre todo que te ayuden.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: devmerz
github_username:  devmerz

# Build settings
markdown: kramdown
